### ISSUE TITLE
process_file_async throws when passing in a text file as input

### ISSUE THREAD

**Issue by clande** [power-of-language/oneai_sdk_python#5]
[Line 52](https://github.com/oneai-nlp/oneai-python/blob/829322167425797196057cbcdf90389d6ec8a253/src/oneai/process_scheduler.py#L52) is throwing because input.text is just a string primitive and doesn't have a name attribute.

[Here's](https://github.com/clande/demo/blob/cffba5914fe7ea690cdd5731d73b8a3da9d926ce/oneai_demo.py) some code that repros the issue.

**Comment by michgur** [comment]
fixed in version 0.9.70

thanks for the report!
